export default {
  video: {
    position: 'relative',
    flex: 1,
    margin: "auto",
    color: "inherit",
    textDecoration: "none",
    textAlign: "center",
    display: "flex",
    justifyContent: "stretch",
    alignItems: "stretch",
    flexDirection: "column",
    backgroundColor: 'Transparent',
  },
  innerWrap: {
    height: '94vw',
    width: '94vw',
    maxHeight: 400,
    maxWidth: 400,
    margin: 'auto',
    // borderRadius: 20,
    boxShadow: "1px 1px 20px rgba(0,0,0,0.2)",
    position: 'relative',
    flex: 1,
    display:'block',
    overflow: "hidden",
  },
  tools: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
}
