export default {
  wrap: {
    display: "flex",
    // flexWrap: 'wrap',
    flexDirection: "column",
    zIndex: 1001,
    // backgroundColor: "#FFF",
    overflow: "auto",
    margin: "auto",
    borderRadius: "0 0 15px 15px",
  },
  video: {
    position: 'relative',
    flex: 1,
    color: "inherit",
    textDecoration: "none",
    textAlign: "center",
    borderRadius: 10,
    margin: "5px 5px 0 0",
    display: "flex",
    justifyContent: "stretch",
    alignItems: "stretch",
    height: 110,
    backgroundColor: 'Transparent',
    border: 0,
  },
  inner: {
    margin: "auto",
    display:'block',
    width: 100,
    height: 100,
    borderRadius: "100%",
    backgroundColor: "#76FF03",
    border: "2px solid #FCE4EC",
    color: "#FFF",
    fontWeight: 600,
    lineHeight: "100px",
    fontSize: 20,
    textDecoration: "none",
  },
}
