export default {
  wrap: {
    display: "flex",
    // flexWrap: 'wrap',
    flexDirection: "column",
    zIndex: 1001,
    // backgroundColor: "#FFF",
    overflow: "auto",
    margin: "auto",
    borderRadius: "0 0 15px 15px",
  },
  video: {
    position: 'relative',
    flex: 1,
    height: 300,
    color: "inherit",
    textDecoration: "none",
    textAlign: "center",
    border: "1px solid #111",
    borderRadius: 10,
    backgroundColor: "#191919",
    margin: "5px 5px 0 0",
    display: "flex",
    justifyContent: "stretch",
    alignItems: "stretch",
  },
  create: {
    height: 50,
    backgroundColor: 'Transparent',
    border: 0,
  },
  offset: {
    marginTop: -195,
  },
  inner: {
    flex: 1,
    display:'block',
    width: 140,
    color: "#424242",
    textDecoration: "none",
  },
  createInner: {
    // backgroundColor: "#76FF03",
    color: "#76FF03",
    fontWeight: 600,
    lineHeight: "50px",
    fontSize: 20,
    textDecoration: "underline",
  },
  editor: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    display: 'flex',
    flexDirection: 'row-reverse',
    zIndex: 100,
  },
}
