export default {
  wrap: {
    position: "relative",
    width: "100%",
    display: "none",
  },
  isActive: {
    display: "block",
  },
  input: {
    width: "100%",
    backgroundColor: "Transparent",
    borderStyle: "none",
    borderColor: "Transparent",
    borderBottom: "1px solid #212121",
    borderRadius: 0,
    fontSize: 18,
    fontWeight: 600,
    fontFamily: "inherit",
    padding: "20px 70px 20px 10px",
    boxSizing: "border-box",
    margin: "0 0 -5px 0",
    resize: "none",
    outline: "none",
  },
  button: {
    padding: "7px 21px",
    display: "inline-block",
    fontSize: 14,
    textAlign: "center",
    border: 0,
    borderRadius: 10,
    backgroundColor: "#E0E0E0",
    color: "#9E9E9E",
    outline: "none",
  },
  buttonActive: {
    backgroundColor: "#8BC34A",
    color: "#FFF",
  },
  inputButton: {
    position: "absolute",
    top: 14,
    right: 10,
    height: 34,
    padding: '0 10px',
    display: "block",
    fontSize: 10,
    lineHeight: "12px",
    textAlign: "center",
    border: 0,
    borderRadius: 15,
    backgroundColor: "#F44336",
    // color: "#9E9E9E",
    color: "#FFF",
    border: "1px solid #FFF",
  },
  inputButtonActive: {
    backgroundColor: "#00E676",
    color: "#FFF",
  },
}
